#whether to show message to other players
# other players will not be able to steal the stuff, though 
globalMsg: true

#whether to show message to players in other worlds, not considering _nether and _the_end variants
doOtherWorlds: false

#whether to show messages to players in other dimensions of the same world
doOtherDimensions: false

#how long since last entity damage to consider 'in combat'
combatTime: 5

#DO NOT TOUCH VERSION NUMBER
version: 1.0
