name: DeathMessages
main: DeathMessages.DeathMessages.DeathMessages
version: 0.0.1
api-version: 1.13
author: leaf26
website: https://github.com/DailyStruggle

softdepend: [PlaceholderAPI]

commands:
    deathMsg:
        description: deathMsg help
        usage: |
            /deathMsg
    deathMsg help:
        description: deathMsg help
        permission: deathMsg.see
        usage: |
            /deathMsg help
    deathMsg test:
        description: test a death message
        permission: deathMsg.test
        usage: |
            /deathMsg test
    deathMsg reload:
        description: Reloads the plugin configuration files
        permission: deathMsg.reload
        usage: |
            /deathMsg reload

permissions:
    deathMsg.*:
        description: allows use of all deathMsg DeathMessages.commands
        default: op
        children:
            deathMsg.see: true
            deathMsg.reload: true
            deathMsg.wakeup: true
    deathMsg.see:
        description: can see the deathMsg help menu
        default: true
    deathMsg.reload: 
        description: can reload deathMsg options
        default: op
    deathMsg.test:
        description: can test death messages randomly or by name
        default: true
    deathMsg.defaultmessage:
        description: can reload deathMsg options
        default: false
    deathMsg.ignore:
        description: ignore player entirely
        default: false
    